# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

# Uncomment this line if you're using Swift
use_frameworks!

target 'Espresso' do
	pod 'RxOptional'
	pod 'Alamofire'
	pod 'RxCocoa'
	pod 'RxSwift'
	pod 'SwiftyJSON'
	pod 'ObjectMapper'
end

